apiVersion: v1
data:
  config.toml: |-
    [Gcs]
    ServiceAccountFilePath = "/etc/gcs-proxy/sa.json"
    Buckets = { "b1" = "loadballancer-test-bucket" }

    [Web]
    Port = 9999
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: gcs-proxy
