apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-pod
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: ["/bin/sh", "-c", "ls /etc/gcs-proxy/"]
      volumeMounts:
        - name: config-volume-1
          mountPath: "/etc/gcs-proxy/sa.json"
          subPath: "sa.json"
          readOnly: true
        - name: config-volume-2
          mountPath: "/etc/gcs-proxy/config.toml"
          subPath: "config.toml"
          readOnly: true
  volumes:
    - name: config-volume-1
      secret:
        secretName: gcs-proxy
        items:
          - key: sa.json
            path: sa.json
    - name: config-volume-2
      configMap:
        name: gcs-proxy
        items:
          - key: config.toml
            path: config.toml
  restartPolicy: Never
