apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "gcs-proxy.namespace" . }}
  name: {{ include "gcs-proxy.fullname" . }}
  labels:
{{ include "gcs-proxy.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "gcs-proxy.fullname" . }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "gcs-proxy.fullname" . }}
    spec:
      containers:
        - name: gcs-proxy
          image: {{ .Values.image.repository  }}
          args:
            - "/etc/gcs-proxy/config.toml"
          ports:
            - name: http
              containerPort: {{ .Values.gcs_proxy.port }}
              protocol: TCP
          volumeMounts:
            - name: config-volume-1
              mountPath: "/etc/gcs-proxy/sa.json"
              subPath: "sa.json"
              readOnly: true
            - name: config-volume-2
              mountPath: "/etc/gcs-proxy/config.toml"
              subPath: "config.toml"
              readOnly: true
      volumes:
        - name: config-volume-1
          secret:
            secretName: {{ include "gcs-proxy.fullname" . }}
            items:
              - key: sa.json
                path: sa.json
        - name: config-volume-2
          configMap:
            name: {{ include "gcs-proxy.fullname" . }}
            items:
              - key: config.toml
                path: config.toml
