apiVersion: v1
data:
  sa.json: {{ required ".Values.gcp_sa_base64 is required! e.g. export GCP_SA=$(cat /path/to/sa.json | base64 -w 0)" .Values.gcp_sa_base64 }}
kind: Secret
metadata:
  creationTimestamp: null
  name: gcs-proxy