apiVersion: v1
kind: Service
metadata:
  name: gcs-proxy
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "gcs-proxy"
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: {{ .Values.gcs_proxy.port }}
  selector:
    app: gcs-proxy
  type: NodePort