apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "gcs-proxy.namespace" . }}
  name: {{ include "gcs-proxy.fullname" . }}
  labels:
{{ include "gcs-proxy.labels" . | indent 4 }}
spec:
  selector:
    app: {{ include "gcs-proxy.fullname" . }}
  ports:
  - protocol: TCP
    port: {{ .Values.gcs_proxy.port }}
    targetPort: http